const SET_USER = 'SET_USER'
const SET_PLAY_SONG_LIST = 'SET_PLAY_SONG_LIST'
const ADD_PLAY_SONG = 'ADD_PLAY_SONG'
const DEL_PLAY_SONG = 'DEL_PLAY_SONG'
const SET_CURR_SONG = 'SET_CURR_SONG'
const SET_LIKE_SONG_LIST = 'SET_LIKE_SONG_LIST'
const ADD_LIKE_SONG = 'ADD_LIKE_SONG'
const DEL_LIKE_SONG = 'DEL_LIKE_SONG'
const SET_SONG_LIST = 'SET_SONG_LIST'
const ADD_SONG_LIST = 'ADD_SONG_LIST'
const DEL_SONG_LIST = 'DEL_SONG_LIST'
const TOGGLE_SONG_DETAIL = 'TOGGLE_SONG_DETAIL'
const TOGGLE_SONG_STATUS = 'TOGGLE_SONG_STATUS'
const SET_VOLUME = 'SET_VOLUME'
const SET_SUGGEST_LIST = 'SET_SUGGEST_LIST'
const ADD_SUGGEST = 'ADD_SUGGEST'
const DEL_SUGGEST = 'DEL_SUGGEST'
const SET_PLAY_TIME = 'SET_PLAY_TIME'

export let actionTypes = {
  SET_USER,
  SET_PLAY_SONG_LIST,
  ADD_PLAY_SONG,
  DEL_PLAY_SONG,
  SET_CURR_SONG,
  SET_LIKE_SONG_LIST,
  ADD_LIKE_SONG,
  DEL_LIKE_SONG,
  SET_SONG_LIST,
  ADD_SONG_LIST,
  DEL_SONG_LIST,
  TOGGLE_SONG_DETAIL,
  TOGGLE_SONG_STATUS,
  SET_VOLUME,
  SET_SUGGEST_LIST,
  ADD_SUGGEST,
  DEL_SUGGEST,
  SET_PLAY_TIME
}

export function createAction (type, payload) {
  return {
    type,
    payload
  }
}
